import { createKarplusStrongVoice,type KarplusStrongVoice } from '../dsp/karplusStrong'
type ScheduledEvent={frame:number;durationFrames:number;type:'metronome'|'note';midi?:number;accent?:boolean;instrument?:'guitar'|'bass'}
interface ActiveVoice{voice:KarplusStrongVoice;endFrame:number}
type WorkletMessage={type:'LOAD_EVENTS';events:ScheduledEvent[]}|{type:'CLEAR_EVENTS'}|{type:'SET_VOLUMES';metronome:number;reference:number}|{type:'STOP'}
declare const currentFrame:number
declare const sampleRate:number
declare abstract class AudioWorkletProcessor{readonly port:MessagePort;abstract process(inputs:Float32Array[][],outputs:Float32Array[][]):boolean}
declare function registerProcessor(name:string,processor:typeof AudioWorkletProcessor):void
class PracticeProcessor extends AudioWorkletProcessor{private events:ScheduledEvent[]=[];private voices:ActiveVoice[]=[];private metronomeVolume=.3;private referenceVolume=.35;private clickPhase=-1;private clickGain=0;private fade=1
  constructor(){super();this.port.onmessage=(e:MessageEvent<WorkletMessage>)=>{const m=e.data;if(m.type==='LOAD_EVENTS'){this.fade=1;this.events=[...this.events,...m.events].sort((a,b)=>a.frame-b.frame)}else if(m.type==='CLEAR_EVENTS')this.events=[];else if(m.type==='SET_VOLUMES'){this.metronomeVolume=m.metronome;this.referenceVolume=m.reference}else{this.events=[];this.fade=.995}}}
  process(_inputs:Float32Array[][],outputs:Float32Array[][]):boolean{const channels=outputs[0];if(!channels?.[0])return true;const length=channels[0].length,end=currentFrame+length;const due=this.events.filter(e=>e.frame>=currentFrame&&e.frame<end);this.events=this.events.filter(e=>e.frame>=end);for(let i=0;i<length;i++){const absoluteFrame=currentFrame+i;for(const event of due)if(event.frame===absoluteFrame){if(event.type==='metronome'){this.clickPhase=0;this.clickGain=(event.accent?1:.65)*this.metronomeVolume}else if(event.midi!==undefined)this.voices.push({voice:createKarplusStrongVoice({midi:event.midi,sampleRate,instrument:event.instrument??'guitar',seed:event.frame}),endFrame:event.frame+event.durationFrames})}let value=0;if(this.clickPhase>=0){value+=Math.sin(this.clickPhase*2*Math.PI*(this.clickPhase<80?1600:900)/sampleRate)*this.clickGain*Math.exp(-this.clickPhase/700);this.clickPhase++;if(this.clickPhase>3000)this.clickPhase=-1}this.voices=this.voices.filter(v=>!v.voice.isFinished()&&absoluteFrame<v.endFrame);for(const active of this.voices){const release=Math.min(1,(active.endFrame-absoluteFrame)/64);value+=active.voice.processSample()*this.referenceVolume*release}value*=this.fade;for(const channel of channels)channel[i]=Math.max(-1,Math.min(1,value))}return true}}
registerProcessor('practice-processor',PracticeProcessor)
