<script setup lang="ts">
import{computed,onBeforeUnmount,onMounted,ref,watch}from'vue';import{useRegisterSW}from'virtual:pwa-register/vue';import type{ExerciseTimeline,InstrumentType,PracticeMode,PracticeRound,ScaleType,ExerciseType,VisualTimelineState}from'../domain/types';import{getTuningPresets}from'../domain/music/tuning';import{randomSeed}from'../domain/random/rng';import{tickToContextTime}from'../domain/timeline/timeline';import{ExerciseWorkerClient}from'../workers/exerciseClient';import{PracticeAudioEngine}from'../audio/practiceAudio';import{getClockSnapshot,estimateAudibleContextTime,timelineTickAtContextTime,getVisualStateAtTick}from'../audio/audioClock';import{createTimingRecorder}from'../debug/timingRecorder';import SettingsPanel from'./SettingsPanel.vue';import ScaleHeader from'./ScaleHeader.vue';import FretboardView from'./FretboardView.vue';import TransportControls from'./TransportControls.vue';import DebugPanel from'./DebugPanel.vue';
const instrument=ref<InstrumentType>('guitar'),stringCount=ref(6),tuningId=ref('guitar-6-standard'),scaleType=ref<ScaleType|'random'>('random'),exerciseType=ref<ExerciseType>('normal'),mode=ref<PracticeMode>('randomPosition'),bpm=ref(100),seed=ref(randomSeed()),playing=ref(false),loading=ref(false),round=ref<PracticeRound|null>(null),visual=ref<VisualTimelineState>({currentEvent:null,nextEvent:null,eventIndex:-1,progress:0}),pathIndex=ref(0),metronomeVolume=ref(.3),referenceVolume=ref(.35),error=ref('');const tuning=computed(()=>getTuningPresets(instrument.value,stringCount.value).find(t=>t.id===tuningId.value)?.midi??getTuningPresets(instrument.value,stringCount.value)[0]?.midi??[]);const selectedScale=computed<ScaleType>(()=>round.value?.combination.scaleType??(scaleType.value==='random'?'major':scaleType.value));const selectedRoot=computed(()=>round.value?.combination.root??0);const currentPath=computed(()=>round.value?.paths[pathIndex.value]?.notes??[]);const audio=new PracticeAudioEngine(),recorder=createTimingRecorder();let worker:ExerciseWorkerClient|null=null,frame=0,sessionStart=0,wakeLock:WakeLockSentinel|null=null,prefetchedRound:Promise<PracticeRound|null>|null=null,lastFramePerformance=0,lastRecordedEvent=-1;const{needRefresh,updateServiceWorker}=useRegisterSW({immediate:true});
watch([instrument,stringCount],()=>{const first=getTuningPresets(instrument.value,stringCount.value)[0];if(first)tuningId.value=first.id});watch([metronomeVolume,referenceVolume],()=>audio.setVolumes(metronomeVolume.value,referenceVolume.value));
async function start(){loading.value=true;error.value='';try{worker?.dispose();worker=new ExerciseWorkerClient();const settings={instrument:instrument.value,tuning:tuning.value,root:0 as const,scaleType:scaleType.value,exerciseType:exerciseType.value,mode:mode.value,bpm:bpm.value,seed:seed.value};await worker.init(settings);round.value=await worker.generateNext();pathIndex.value=0;recorder.clear();lastRecordedEvent=-1;lastFramePerformance=performance.now();const timing=await audio.start(round.value.timeline,bpm.value,instrument.value,{metronome:metronomeVolume.value,reference:referenceVolume.value});sessionStart=timing.sessionStart;playing.value=true;wakeLock=await navigator.wakeLock?.request('screen')??null;prefetchedRound=worker.generateNext(round.value.combination).catch(()=>null);animate()}catch(e){error.value=e instanceof Error?e.message:'Unable to start'}finally{loading.value=false}}
async function advanceRound(){if(!prefetchedRound||!worker){stop();return}try{audio.stop();const next=await prefetchedRound;if(!next||!playing.value){if(!next)stop();return}round.value=next;pathIndex.value=0;lastRecordedEvent=-1;const timing=await audio.start(round.value.timeline,bpm.value,instrument.value,{metronome:metronomeVolume.value,reference:referenceVolume.value});sessionStart=timing.sessionStart;prefetchedRound=worker.generateNext(round.value.combination).catch(()=>null);animate()}catch(e){error.value=e instanceof Error?e.message:'Unable to prepare the next round';stop()}}
function stop(){playing.value=false;cancelAnimationFrame(frame);audio.stop();void wakeLock?.release();wakeLock=null;visual.value={currentEvent:null,nextEvent:null,eventIndex:-1,progress:0}}
function toggle(){if(playing.value)stop();else void start()}
function animate(){const context=audio.audioContext;if(!playing.value||!context)return;const now=performance.now(),snapshot=getClockSnapshot(context),audible=estimateAudibleContextTime(snapshot,now),tick=timelineTickAtContextTime(audible,sessionStart,bpm.value);visual.value=getVisualStateAtTick(round.value?.timeline as ExerciseTimeline,tick);if(visual.value.currentEvent&&visual.value.eventIndex!==lastRecordedEvent){const expected=tickToContextTime(visual.value.currentEvent.tick,bpm.value,sessionStart),visualTarget=snapshot.performanceTime+(expected-snapshot.contextTime)*1000;recorder.record({expectedTime:expected,audioContextTime:context.currentTime,outputContextTime:snapshot.contextTime,performanceTime:now,estimatedAudibleTime:audible,visualTarget,visualActual:now,deviation:(now-visualTarget)/1000,droppedFrames:Math.max(0,Math.round((now-lastFramePerformance)/(1000/60))-1),audioContextState:context.state});lastRecordedEvent=visual.value.eventIndex}lastFramePerformance=now;if(round.value?.paths.length)pathIndex.value=Math.min(round.value.paths.length-1,Math.floor(Math.max(0,tick)/round.value.timeline.totalTicks*round.value.paths.length));if(tick>=(round.value?.timeline.totalTicks??0)){cancelAnimationFrame(frame);void advanceRound();return}frame=requestAnimationFrame(animate)}
function keydown(e:KeyboardEvent){if(e.code==='Space'&&!['INPUT','SELECT','TEXTAREA','BUTTON'].includes((e.target as HTMLElement).tagName)){e.preventDefault();toggle()}}
function visibility(){if(document.hidden&&playing.value)stop()}
onMounted(()=>{window.addEventListener('keydown',keydown);document.addEventListener('visibilitychange',visibility)});onBeforeUnmount(()=>{stop();worker?.dispose();void audio.dispose();window.removeEventListener('keydown',keydown);document.removeEventListener('visibilitychange',visibility)});
</script>
<template><main><div v-if="needRefresh&&!playing" class="update">A new version is ready. <button @click="updateServiceWorker(true)">Update</button></div><ScaleHeader :combination="round?.combination??null"/><SettingsPanel v-model:instrument="instrument" v-model:string-count="stringCount" v-model:tuning-id="tuningId" v-model:scale-type="scaleType" v-model:exercise-type="exerciseType" v-model:mode="mode" v-model:bpm="bpm" :disabled="playing||loading"/><p v-if="error" class="error" role="alert">{{error}}</p><section class="practice"><div class="progress"><span>{{mode==='fullNeck'&&round?`Position ${pathIndex+1} / ${round.paths.length}`:playing?'Practice in progress':'Ready'}}</span><span>{{Math.round(visual.progress*100)}}%</span></div><FretboardView :tuning="tuning" :root="selectedRoot" :scale-type="selectedScale" :path="currentPath" :current="visual.currentEvent?.note??null" :next="visual.nextEvent?.note??null"/><div class="controls"><TransportControls :playing="playing" :loading="loading" @toggle="toggle"/><label>Click <input v-model.number="metronomeVolume" type="range" min="0" max="1" step=".01"></label><label>Reference <input v-model.number="referenceVolume" type="range" min="0" max="1" step=".01"></label></div></section><DebugPanel :seed="seed" :stats="recorder.stats()" :events="round?.debugEvents??[]"/></main></template>
