import type { ExerciseTimeline,FretboardPath,PracticeRound,RoundGenerationContext,ScaleCombination } from '../types'
import { enumeratePositions } from '../fretboard/positionGenerator'
import { generateAllLinkedDiagonals } from '../fretboard/linkedDiagonal'
import { generateContinuousCandidates } from '../fretboard/continuous/candidate'
import { selectDistinctContinuousPaths } from '../fretboard/continuous/search'
import { buildWeightedScaleBag,preventBoundaryDuplicate,shuffleScaleBag } from './weightedBag'
import { createPositionBag,createPositionBagKey,drawPosition,refillPositionBag } from './positionBag'
import { createAscendingExercise,createDescendingExercise } from './pattern'
import { buildExerciseTimeline } from '../timeline/timeline'
function combinations(context:RoundGenerationContext):ScaleCombination[]{if(context.state){if(!context.state.scaleBag.length)context.state.scaleBag.push(...preventBoundaryDuplicate(context.state.previousCombination,shuffleScaleBag(buildWeightedScaleBag(context.settings.scaleType),context.rng)));return context.state.scaleBag}return preventBoundaryDuplicate(context.previousCombination??null,shuffleScaleBag(buildWeightedScaleBag(context.settings.scaleType),context.rng))}
function buildRoundTimeline(context:RoundGenerationContext,paths:readonly FretboardPath[]):ExerciseTimeline{let offset=0;const events:ExerciseTimeline['events'][number][]=[];let ascendingEndTick=0,descendingStartTick=0;for(let index=0;index<paths.length;index++){const path=paths[index] as FretboardPath,part=buildExerciseTimeline({ascending:createAscendingExercise(path.notes,context.settings.exerciseType),descending:createDescendingExercise(path.notes,context.settings.exerciseType),exerciseType:context.settings.exerciseType,previewBars:index===0?1:0});events.push(...part.events.map(event=>({...event,tick:event.tick+offset})));if(index===0){ascendingEndTick=part.ascendingEndTick;descendingStartTick=part.descendingStartTick}offset+=part.totalTicks;if(index<paths.length-1){for(let beat=0;beat<7680;beat+=960)events.push({tick:offset+beat,durationTicks:120,type:'metronome',accent:beat%3840===0});offset+=7680}}return{events:events.sort((a,b)=>a.tick-b.tick),totalTicks:offset,ascendingEndTick,descendingStartTick}}
function round(context:RoundGenerationContext,combination:ScaleCombination,paths:readonly FretboardPath[],debugEvents:readonly string[]):PracticeRound{const first=paths[0];if(!first)throw new RangeError('A round requires at least one path');return{id:`${context.settings.seed}-${combination.root}-${combination.scaleType}-${first.id}`,combination,paths,timeline:buildRoundTimeline(context,paths),debugEvents}}
export function generateRandomPositionRound(context:RoundGenerationContext):PracticeRound{const debug:string[]=[],bag=combinations(context);while(bag.length){const combination=bag.shift() as ScaleCombination,positions=enumeratePositions({tuning:context.settings.tuning,...combination});if(!positions.length){debug.push(`Skipped ${combination.root}/${combination.scaleType}: no valid position`);continue}const key=createPositionBagKey({tuning:context.settings.tuning,...combination}),existing=context.state?.positionBags.get(key),positionBag=existing?.remaining.length?existing:existing?refillPositionBag(positions,context.rng,existing.previousPositionId??undefined):createPositionBag(positions,context.rng),draw=drawPosition(positionBag);if(context.state){context.state.positionBags.set(key,draw.bag);context.state.previousCombination=combination}if(draw.position)return round(context,combination,[{id:draw.position.id,notes:draw.position.ascendingPath}],debug)}throw new RangeError('No valid scale position for the selected settings')}
export function generateFullNeckRound(context:RoundGenerationContext):PracticeRound{const combination=combinations(context).shift();if(!combination)throw new RangeError('Scale bag is empty');if(context.state)context.state.previousCombination=combination;const base={tuning:context.settings.tuning,...combination},positions=enumeratePositions(base).map(p=>({id:p.id,notes:p.ascendingPath})),linked=generateAllLinkedDiagonals(base),candidates=generateContinuousCandidates({...base,seed:context.settings.seed}),continuous=selectDistinctContinuousPaths(candidates,[...positions,...linked,...(context.excludedPaths??[])]),paths=[...positions,...linked,...continuous];if(!paths.length)throw new RangeError('No full-neck paths available');return round(context,combination,paths,[])}
export function generateNextRound(context:RoundGenerationContext):PracticeRound{return context.settings.mode==='fullNeck'?generateFullNeckRound(context):generateRandomPositionRound(context)}
